package com.example.demo.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table student
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Student{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sage
     *
     * @mbg.generated
     */
    private Date sage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Ssex
     *
     * @mbg.generated
     */
    private String ssex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sid
     *
     * @return the value of student.Sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sid
     *
     * @param sid the value for student.Sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sname
     *
     * @return the value of student.Sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sname
     *
     * @param sname the value for student.Sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sage
     *
     * @return the value of student.Sage
     *
     * @mbg.generated
     */
    public Date getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sage
     *
     * @param sage the value for student.Sage
     *
     * @mbg.generated
     */
    public void setSage(Date sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Ssex
     *
     * @return the value of student.Ssex
     *
     * @mbg.generated
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Ssex
     *
     * @param ssex the value for student.Ssex
     *
     * @mbg.generated
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }
}