package com.example.demo.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table stuname
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class StuName {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuname.stuId
     *
     * @mbg.generated
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuname.studentName
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuname.stuNameId
     *
     * @mbg.generated
     */
    private Integer stuNameId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuname.stuId
     *
     * @return the value of stuname.stuId
     *
     * @mbg.generated
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuname.stuId
     *
     * @param stuId the value for stuname.stuId
     *
     * @mbg.generated
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuname.studentName
     *
     * @return the value of stuname.studentName
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuname.studentName
     *
     * @param studentName the value for stuname.studentName
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuname.stuNameId
     *
     * @return the value of stuname.stuNameId
     *
     * @mbg.generated
     */
    public Integer getStuNameId() {
        return stuNameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuname.stuNameId
     *
     * @param stuNameId the value for stuname.stuNameId
     *
     * @mbg.generated
     */
    public void setStuNameId(Integer stuNameId) {
        this.stuNameId = stuNameId;
    }
}